app:
  name: basketball-stats-service
  version: 0.1.0
  env: development
  port: 8080

logger:
  level: debug                 # debug, info, warn, error
  format: json                 # json, console
  output_target: stdout        # stdout, stderr, file
  file_path: logs/app.log      # used when output_target = file
  time_format: rfc3339         # rfc3339, unix, epoch
  with_caller: true
  stacktrace: false
  stacktrace_min_level: error  # error, fatal, panic
  fields:
    service: basketball
    module: stats

postgres:
  host: localhost
  port: 5432
  sslmode: disable
  max_conns: 10
  min_conns: 2
  max_conn_lifetime: 1800   # seconds
  max_conn_idle_time: 300   # seconds
  health_check_period: 30   # seconds

http:
  read_timeout: 5s
  write_timeout: 10s
  idle_timeout: 120s
  max_header_bytes: 1048576
