version: "3.9"

services:
  db:
    image: postgres:16
    container_name: basketball_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: basketball
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: basketball_app
    depends_on:
      - db
    ports:
      - "8080:8080"

volumes:
  db_data:
